const I18N = {
  en: {
    ann: "A Limassol edit · Men and women · Partner houses · Cyprus and EU",
    shop: "Shop", men: "Men", women: "Women", new: "New", lookbook: "Lookbook", about: "House",
    bag: "Bag", shopMen: "Shop Men", shopWomen: "Shop Women",
    heroKicker: "Limassol Atelier · SS26",
    heroTitle: "Quiet luxury with a Mediterranean cut.",
    heroText: "Glamour is a bilingual house for men’s and women’s clothing — linen, tailoring, silk and evening pieces designed for heat, light and city nights.",
    heroCard: "Limassol light. European cut.",
    drop: "The first drop", dropSub: "Affiliate edit — Erverte, Viaduct, Talbot, Misciano. Buy on the partner store.",
    all: "All", shirts: "Shirts", tailoring: "Tailoring", dresses: "Dresses", knit: "Knit",
    houses: "Houses", housesTitle: "About the houses",
    housesText: "Affiliate-only. Live partner houses: Erverte Paris, Viaduct Clothing, Talbot Runhof and Misciano Paris — you buy on their sites via Awin.",
    livePartnersTitle: "Live partner houses",
    livePartnersText: "Accepted programmes only. Buy on the brand store.",
    viaductBlurb: "United Kingdom. Trainers and sport.",
    erverteBlurb: "France. Contemporary menswear in natural fibres.",
    menCol: "Men", womenCol: "Women",
    menLine: "Sharp, breathable, unforced.", womenLine: "Sculpted ease. Evening-ready.",
    quizTitle: "Find your cut", quizText: "A 10-second stylist. Choose the mood — we recommend a first edit.",
    q1: "Coast day", q2: "City tailoring", q3: "Gallery night", q4: "Soft knit weekend",
    newsTitle: "Private first look", newsText: "Join the list for the Cyprus drop, fittings in Limassol and bilingual lookbooks.",
    email: "Email address", join: "Join",
    aboutTitle: "The house.",
    aboutText: "Glamour is a bilingual (EN/EL) menswear and womenswear edit in Limassol, Cyprus. Quiet luxury with a Mediterranean cut. We promote selected European houses and send traffic to the brand store — the customer buys on their site. Affiliate only: no wholesale stock, no dropship.",
    trust1: "Cyprus studio", trust2: "EN / EL", trust3: "WhatsApp +357 99 661190", trust4: "Returns with the partner brand",
    contactTitle: "Contact the house",
    contactText: "Partnerships and press — write or call.",
    polTitle: "How we work", polShip: "How you buy",
    polShipD: "You shop the edit here. When a partner is live, checkout is on the brand site. They ship.",
    polRet: "Returns", polRetD: "Returns follow the partner brand policy once you buy on their site.",
    polPriv: "Privacy", polPrivD: "We keep enquiry emails to run the house. No lists sold. Newsletter is opt-in only.",
    add: "View piece", size: "Size", close: "Close", empty: "Your bag is empty.", total: "Total",
    checkout: "Request this look", added: "Added to bag", partners: "Partners",
    partTitle: "Sell with Glamour",
    partText: "We present your pieces. The customer buys on your site.",
    m1t: "Affiliate", m1d: "We send traffic to your shop. You fulfil.",
    m2t: "Consignment", m2d: "Only if we later agree.",
    m3t: "Wholesale", m3d: "Only if we later agree to a capsule.",
    pBrand: "Brand name", pNote: "Collection, price range", pApply: "Apply as partner",
    soldBy: "Presented by", yourCut: "House",
    /* i18n-draft: strings that were hardcoded in index.html / JS */
    docTitle: "Glamour — Quiet luxury, Mediterranean cut",
    region: "CY / EU",
    lookNav: "Look",
    storesNav: "Stores",
    mobileNavLabel: "Mobile",
    heroAlt1: "Erverte Straight Fit Shirt",
    heroAlt2: "Talbot Runhof Ball Gown Couplet5",
    heroAlt3: "Viaduct adidas Originals Itasca 22 Windbreaker",
    tileErverteDesc: "Made in France",
    tileErverte: "Affiliate partner · Shop directly with Erverte Paris",
    tileViaductDesc: "Trainers & sport",
    tileViaduct: "Affiliate partner · Shop directly with Viaduct Clothing",
    tileTalbotDesc: "Evening / occasion",
    tileTalbot: "Affiliate partner · Shop directly with Talbot Runhof",
    /* Misciano Paris (Awin 117185) — draft */
    tileMiscianoDesc: "Designed in Paris · Made in Tuscany",
    tileMisciano: "Affiliate partner · Shop directly with Misciano Paris",
    miscianoBlurb: "France. Womenswear designed in Paris, made in Tuscany.",
    shopMisciano: "Affiliate partner · Shop directly with Misciano Paris",
    shopsMisciano: "France. Womenswear designed in Paris, made in Tuscany. Buy on their store.",
    shopsMiscianoLink: "Affiliate partner · Shop directly with Misciano Paris",
    miscianoText: "Partner house. Womenswear designed in Paris, made in Tuscany — dresses, ready-to-wear and accessories in a quiet, fluid line. You buy on their store.",
    mDraped: "Draped beige crepe dress with contrasting neckline",
    mCowlLong: "Long black dress with a plunging cowl neck and ties",
    mSageSatin: "Sage green satin midi dress with cowl neckline",
    mRibKnit: "Black ribbed knit midi dress",
    mCrepe: "Crepe",
    mEvening: "Evening",
    mSatin: "Satin",
    mKnit: "Knit",
    mChampagne: "Champagne pearl and sequin midi dress",
    mAsymLong: "Long black dress with asymmetrical neckline",
    mPleatedPink: "Long pleated dress in powder pink chiffon",
    mGreenCorset: "Long green evening dress with beaded corset",
    mSequins: "Sequins",
    mChiffon: "Chiffon",
    mTulle: "Tulle",
    shopErverte: "Affiliate partner · Shop directly with Erverte Paris",
    shopViaduct: "Affiliate partner · Shop directly with Viaduct Clothing",
    shopTalbot: "Affiliate partner · Shop directly with Talbot Runhof",
    openEdit: "Open edit",
    talbotBlurb: "Germany. Evening / occasion womenswear, Munich. Buy on their store.",
    also: "Also",
    shopTheirStore: "Shop their store",
    lookEyebrow: "Quiet luxury edit",
    lookTitle: "Create the Look",
    lookSub: "Quiet luxury, in three moves.",
    lookName1: "Blazer Rush3",
    lookName2: "White Cotton T-Shirt – Made in France",
    lookName3: "adidas Originals Women's Court Tourino Shoes - White",
    lookPrice3: "£54.99 (was £75.00)",
    buy: "Shop",
    affLinks: "Affiliate links.",
    shopsTitle: "Partner shops",
    shopsText: "Only houses that are live on Glamour. Pending programmes are not listed.",
    shopsErverte: "France. Menswear in natural fibres, made in France. Buy on their store.",
    shopsErverteLink: "Affiliate partner · Shop directly with Erverte Paris",
    shopsViaduct: "United Kingdom. Trainers and sport. Buy on their store.",
    shopsViaductLink: "Affiliate partner · Shop directly with Viaduct Clothing",
    shopsTalbotLink: "Affiliate partner · Shop directly with Talbot Runhof",
    nextTitle: "Next houses",
    nextText: "European brands appear here when the programme is accepted.",
    seeAll: "See all",
    showLess: "Show less",
    onStore: "Shop on their store",
    ctaErverte: "Affiliate partner · Shop directly with Erverte Paris",
    ctaViaduct: "Affiliate partner · Shop directly with Viaduct Clothing",
    ctaTalbot: "Affiliate partner · Shop directly with Talbot Runhof",
    ctaMisciano: "Affiliate partner · Shop directly with Misciano Paris",
    talbotText: "DE · evening / occasion womenswear, Munich. Affiliate — shop on their store.",
    nSommerhit2: "Evening Dress Sommerhit2",
    nSolite1: "Evening Dress Solite1",
    nKortney1: "Cocktail Dress Kortney1",
    nSocialclub6: "Evening Dress Socialclub6",
    nMobina2: "Evening Dress Mobina2",
    nSodium2: "Evening Dress Sodium2",
    nSocialclub3: "Evening Dress Socialclub3",
    nTolga12: "Evening Dress Tolga12",
    seeAllTalbot: "See all Talbot in Shop",
    shopAllTalbot: "Affiliate partner · Shop directly with Talbot Runhof",
    lbAlt1: "NATALLIA CUT · ivory wall · full look",
    lbAlt2: "NATALLIA CUT · Limassol Marina · full look",
    lbAlt3: "NATALLIA CUT · terracotta sage · full look",
    lbDots1: "Lookbook slides",
    lbTitle1: "NATALLIA CUT · Limassol",
    lbText1: "Quiet luxury. Editorial.",
    lbAlt4: "Natallia Cut · Evening · Limassol · black boat-neck",
    lbAlt5: "Natallia Cut · Evening · Limassol · red dress",
    lbAlt6: "Natallia Cut · Evening · Limassol · navy dress",
    lbDots2: "Natallia Cut Evening slides",
    lbTitle2: "Natallia Cut · Evening · Limassol",
    lbCta: "Affiliate partner · Shop directly with Talbot Runhof",
    lbAlt7: "RODOULA CUT · Evening · ivory satin",
    lbAlt8: "RODOULA CUT · Evening · ivory satin volume",
    lbAlt9: "RODOULA CUT · Evening · navy one-shoulder",
    lbAlt10: "RODOULA CUT · Evening · red strapless mermaid",
    lbAlt11: "RODOULA CUT · Evening · black wrap marina",
    lbDots3: "Rodoula Evening slides",
    lbTitle3: "RODOULA CUT · Evening",
    lbText3: "Munich light. Limassol.",
    slide: "Slide",
    viaductText: "Partner house. Men, women, trainers. You buy on their store.",
    whiteBlue: "White / Blue",
    vAltWhite: "Nike Tech Windrunner white",
    vAltTartan: "adidas tartan jacket",
    vTartan: "adidas Tartan jacket",
    vAltShorts: "adidas shorts",
    vShorts: "adidas Climacool shorts",
    vTisch: "adidas Tischtennis trainers",
    vAltTisch: "adidas Originals Tischtennis trainers black",
    vNatTennis: "adidas National Tennis OG",
    vAltNatTennis: "adidas Originals National Tennis OG shoes white",
    vCoach: "adidas corduroy coach jacket",
    vAltCoach: "adidas Originals corduroy coach jacket brown",
    vPuffer: "adidas down puffer jacket",
    vAltPuffer: "adidas Essentials down puffer jacket black",
    newIn: "New in",
    newInText: "Latest drop on Viaduct.",
    openNewIn: "Open new in",
    menText: "Jackets, hoodies, sport.",
    openMen: "Open menswear",
    womenText: "Womenswear and trainers.",
    openWomen: "Open womenswear",
    footwear: "Footwear",
    openFootwear: "Open footwear",
    shopAllViaduct: "Affiliate partner · Shop directly with Viaduct Clothing",
    erverteText: "Partner house. High-end menswear in natural fibres, made in France. You buy on their store.",
    eGeo: "Geometric Harmony Linen Shirt",
    madeInFrance: "Made in France",
    eGreyHoodie: "Grey hoodie",
    organicCotton: "Organic cotton",
    eAltPolo: "Navy polo",
    ePolo: "Navy organic polo",
    eAltTee: "Navy T-shirt",
    eTee: "Navy cotton T-shirt",
    eLinenOversized: "Linen oversized shirt",
    eAltLinenOversized: "Linen oversized shirt",
    eLinenTee: "Organic French linen T-shirt",
    eAltLinenTee: "Linen T-shirt",
    eLinenShorts: "Linen shorts",
    eAltLinenShorts: "Linen shorts",
    linen100: "100% linen",
    eAllText: "Full Erverte collection.",
    openAll: "Open all",
    eShirtsText: "Linen and silk shirts.",
    openShirts: "Open shirts",
    theHouse: "The house",
    theHouseText: "Natural fibres, made in France.",
    aboutErverte: "About Erverte",
    shopAllErverte: "Affiliate partner · Shop directly with Erverte Paris",
    sizesTitle: "EU size guide · Cyprus & EU",
    sizesText: "House pieces use EU numbering. Partner stores use their own chart at checkout.",
    limassol: "Limassol",
    oneSite: "One site, two languages.",
    tluxyText: "European multi-brand store",
    tluxyAlt: "T.LUXY logo",
    pitodText: "Sustainable fashion · Genderless basics in organic cotton",
    pitodAlt: "Pitod organic cotton hoodie",
    alvieroText: "Italian heritage · Signature Geo map-print bags & accessories",
    alvieroAlt: "Alviero Martini Geo Classic oblong shoulder bag",
    coesText: "British independent since 1928 · Fashion, footwear & sportswear",
    coesAlt: "Coes – fashion, footwear & sportswear",
    openStore: "Open store",
    footPlace: "Limassol · Cyprus",
    shopsLink: "Shops",
    sizesLink: "Sizes",
    contactH: "Contact",
    followH: "Follow",
    audioPlay: "Play",
    audioMute: "Mute",
    audioHint: "click play/pause · double-click next",
    /* Legal baseline 2026-10-02: cookie banner, footer legal links, /privacy /cookies /terms /imprint */
    lgPrivacy: "Privacy", lgCookies: "Cookies", lgTerms: "Terms", lgImprint: "Imprint", lgCookieSettings: "Cookie settings",
    ckLabel: "Cookie consent",
    ckText: "We use essential cookies to run this site. Optional cookies (analytics, affiliate) load only if you accept.",
    ckAccept: "Accept", ckReject: "Reject optional", ckSettings: "Settings", ckSave: "Save",
    ckEssential: "Essential", ckEssentialD: "Language and cookie choice. Always on.",
    ckAnalytics: "Analytics", ckAnalyticsD: "Visit statistics. Off unless you turn it on.",
    ckAffiliate: "Affiliate", ckAffiliateD: "Awin click measurement for partner stores. Off unless you turn it on.",
    lastUpdated: "Last updated: 2 October 2026",
    backHome: "← Back to Glamour",
    pvDocTitle: "Privacy notice — Glamour",
    pvMeta: "How Glamour (www.glamourcy.com) handles personal data: what we collect, why, where it goes, your GDPR rights and retention.",
    pvTitle: "Privacy notice",
    pvIntro: "This notice explains what personal data www.glamourcy.com handles, why, and what your rights are.",
    pvCtrlH: "Who is responsible",
    pvCtrl: "Marinos Protopapas, Glamour, Limassol, Cyprus.",
    emailLabel: "Email:",
    pvCollectH: "What we collect",
    pvC1: "Your email address and message, if you write to us.",
    pvC2: "Technical logs recorded by our hosting provider when you visit the site (for example IP address, browser type and time of the request).",
    pvC3: "Your cookie choice, stored in your browser.",
    pvWhyH: "Why we use it",
    pvW1: "To run the site.",
    pvW2: "To reply to your messages.",
    pvW3: "For affiliate measurement, only after you press Accept.",
    pvWhereH: "Where your data goes",
    pvP1: "Vercel — hosting of the site.",
    pvP2: "Awin — affiliate click tracking, only if you press Shop and continue to a partner store.",
    pvNoSellH: "What we don't do",
    pvNoSell: "We do not sell your data. We have no checkout of our own: any purchase happens on the partner house's site.",
    pvRightsH: "Your rights (GDPR)",
    pvRights: "You can ask to access, correct or delete your personal data. Write to us at the email above. You also have the right to lodge a complaint with the Commissioner for Personal Data Protection, Cyprus.",
    pvRetH: "How long we keep data",
    pvR1: "Technical logs: as long as our hosting provider requires.",
    pvR2: "Messages: until the matter is closed.",
    pvR3: "Cookie choice: in your browser, until you change or clear it.",
    pvMoreCookies: "Read the cookie policy",
    cpDocTitle: "Cookie policy — Glamour",
    cpMeta: "Which cookies Glamour (www.glamourcy.com) uses: essential language and consent storage, and optional affiliate and analytics cookies only after you accept.",
    cpTitle: "Cookie policy",
    cpIntro: "This site uses cookies and similar browser storage. Essential ones are always on; optional ones load only after you accept.",
    cpEssH: "Essential (always on)",
    cpEss: "Your language (EN/EL) and your cookie choice. They are stored in your browser and are needed for the site to work.",
    cpOptH: "Optional (only after Accept)",
    cpOpt1: "Affiliate: Awin click cookies, which let a partner store credit a purchase to Glamour.",
    cpOpt2: "Analytics: visit statistics. No analytics tool runs on the site today; if we add one, it will load only after you accept.",
    cpChangeH: "How to change your choice",
    cpChange: "Use the “Cookie settings” button in the footer of any page. It reopens the settings so you can change your choice at any time.",
    cpOpen: "Open cookie settings",
    tmDocTitle: "Terms of use — Glamour",
    tmMeta: "Terms of use for Glamour (www.glamourcy.com): an edit, not a store. Purchases, payment, shipping and returns happen on each partner house's site.",
    tmTitle: "Terms of use",
    tm1H: "An edit, not a store",
    tm1: "Glamour is an edit, not a store. We present selected pieces from partner houses.",
    tm2H: "Buying",
    tm2: "Purchase, payment, shipping, returns and sizing happen on the house's own site, under that house's terms.",
    tm3H: "Prices",
    tm3: "Prices may change on the house's site. The price shown there at checkout is the one that applies.",
    tm4H: "Affiliate links",
    tm4: "We earn a commission if you buy through an affiliate link. It does not change your price.",
    tm5H: "Photos",
    tm5: "Lookbook photos are editorial. The product you buy is the one shown in the house's store.",
    tmContactH: "Questions",
    imDocTitle: "Imprint — Glamour",
    imMeta: "Imprint of Glamour (www.glamourcy.com): Marinos Protopapas, Limassol, Cyprus. Contact by email.",
    imTitle: "Imprint",
    imName: "Name", imBrand: "Brand", imPlace: "Location", imPlaceV: "Limassol, Cyprus", imEmail: "Email", imWeb: "Website",
    rec: { coast: "Start with washed linen and open collars.", city: "Build one sharp column.", night: "Go sculpted.", knit: "Keep it quiet." }
  },
  el: {
    ann: "Επιλογή Λεμεσού · Άνδρες και γυναίκες · Οίκοι συνεργάτες · Κύπρος και ΕΕ",
    shop: "Κατάστημα", men: "Άνδρες", women: "Γυναίκες", new: "Νέα", lookbook: "Λεύκωμα", about: "Οίκος",
    bag: "Τσάντα", shopMen: "Άνδρες", shopWomen: "Γυναίκες",
    heroKicker: "Ατελιέ Λεμεσός · Άνοιξη–\u2060Καλοκαίρι\u00a02026",
    heroTitle: "Ήσυχη πολυτέλεια, μεσογειακή γραμμή.",
    heroText: "Η Glamour είναι δίγλωσσος οίκος αντρικής και γυναικείας μόδας.",
    heroCard: "Φως Λεμεσού. Ευρωπαϊκή γραμμή.",
    drop: "Η πρώτη συλλογή", dropSub: "Επιλογή από οίκους συνεργάτες — Erverte, Viaduct, Talbot, Misciano. Αγορά στο κατάστημα της φίρμας.",
    all: "Όλα", shirts: "Πουκάμισα", tailoring: "Ραπτική", dresses: "Φορέματα", knit: "Πλεκτά",
    houses: "Οίκοι", housesTitle: "Σχετικά με τους οίκους",
    housesText: "Μόνο μέσω συνεργατών. Ενεργοί οίκοι: Erverte Paris, Viaduct Clothing, Talbot Runhof και Misciano Paris — η αγορά γίνεται στον δικό τους ιστότοπο μέσω Awin.",
    livePartnersTitle: "Ενεργοί οίκοι συνεργάτες",
    livePartnersText: "Μόνο αποδεκτά προγράμματα. Η αγορά γίνεται στο κατάστημα της φίρμας.",
    viaductBlurb: "Ηνωμένο Βασίλειο. Αθλητικά παπούτσια και σπορ.",
    erverteBlurb: "Γαλλία. Σύγχρονα ανδρικά σε φυσικές ίνες.",
    menCol: "Άνδρες", womenCol: "Γυναίκες",
    menLine: "Καθαρή γραμμή.", womenLine: "Έτοιμη για βράδυ.",
    quizTitle: "Βρες τη γραμμή σου", quizText: "Διάλεξε διάθεση.",
    q1: "Μέρα", q2: "Πόλη", q3: "Βράδυ", q4: "Πλεκτό",
    newsTitle: "Ιδιωτική πρώτη ματιά", newsText: "Γράψου στη λίστα για τη συλλογή της Κύπρου, τις προβές στη Λεμεσό και τα δίγλωσσα λευκώματα.",
    email: "Email", join: "Εγγραφή",
    aboutTitle: "Ο οίκος.",
    aboutText: "Η Glamour είναι δίγλωσση (ελληνικά/αγγλικά) επιλογή ανδρικής και γυναικείας μόδας στη Λεμεσό. Ήσυχη πολυτέλεια, μεσογειακή γραμμή. Προωθούμε επιλεγμένους ευρωπαϊκούς οίκους και στέλνουμε κίνηση στο δικό τους κατάστημα — η αγορά γίνεται εκεί. Μόνο συνεργασίες προώθησης: χωρίς απόθεμα χονδρικής, χωρίς αποστολές για λογαριασμό τρίτων.",
    trust1: "Στούντιο Κύπρου", trust2: "Ελληνικά / Αγγλικά", trust3: "WhatsApp +357 99 661190", trust4: "Επιστροφές στη φίρμα",
    contactTitle: "Επικοινωνία", contactText: "Συνεργασίες και τύπος.",
    polTitle: "Πώς δουλεύουμε", polShip: "Πώς αγοράζεις",
    polShipD: "Βλέπεις την επιλογή εδώ. Η αγορά γίνεται στον ιστότοπο της φίρμας.",
    polRet: "Επιστροφές", polRetD: "Ισχύουν οι όροι της φίρμας.",
    polPriv: "Απόρρητο", polPrivD: "Δεν πωλούμε λίστες.",
    add: "Δες το κομμάτι", size: "Μέγεθος", close: "Κλείσιμο", empty: "Η τσάντα είναι άδεια.", total: "Σύνολο",
    checkout: "Ζήτησε αυτό το look", added: "Μπήκε", partners: "Συνεργάτες",
    partTitle: "Πούλησε μέσω Glamour",
    partText: "Παρουσιάζουμε τα κομμάτια. Η αγορά γίνεται στο δικό σας κατάστημα.",
    m1t: "Affiliate", m1d: "Στέλνουμε κίνηση. Εσείς πουλάτε.",
    m2t: "Consignment", m2d: "Μόνο αν συμφωνήσουμε μετά.",
    m3t: "Wholesale", m3d: "Μόνο με συμφωνία.",
    pBrand: "Όνομα φίρμας", pNote: "Συλλογή", pApply: "Αίτηση",
    soldBy: "Παρουσίαση", yourCut: "Οίκος",
    /* i18n-draft: strings that were hardcoded in index.html / JS */
    docTitle: "Glamour — Ήσυχη πολυτέλεια, μεσογειακή γραμμή",
    region: "Κύπρος / ΕΕ",
    lookNav: "Σύνολο",
    storesNav: "Μπουτίκ",
    mobileNavLabel: "Μενού κινητού",
    heroAlt1: "Erverte · Ίσιο βαμβακερό πουκάμισο",
    heroAlt2: "Talbot Runhof · Βραδινή τουαλέτα Couplet5",
    heroAlt3: "Viaduct · Αντιανεμικό μπουφάν adidas Originals Itasca 22",
    tileErverteDesc: "Γαλλική κατασκευή",
    tileErverte: "Συνεργάτης · Αγόρασε απευθείας από Erverte Paris",
    tileViaductDesc: "Αθλητικά παπούτσια & σπορ",
    tileViaduct: "Συνεργάτης · Αγόρασε απευθείας από Viaduct Clothing",
    tileTalbotDesc: "Βραδινά & επίσημα",
    tileTalbot: "Συνεργάτης · Αγόρασε απευθείας από Talbot Runhof",
    /* Misciano Paris (Awin 117185) — draft */
    tileMiscianoDesc: "Σχεδιασμός στο Παρίσι · Κατασκευή στην Τοσκάνη",
    tileMisciano: "Συνεργάτης · Αγόρασε απευθείας από Misciano Paris",
    miscianoBlurb: "Γαλλία. Γυναικεία ένδυση σχεδιασμένη στο Παρίσι, φτιαγμένη στην Τοσκάνη.",
    shopMisciano: "Συνεργάτης · Αγόρασε απευθείας από Misciano Paris",
    shopsMisciano: "Γαλλία. Γυναικεία ένδυση σχεδιασμένη στο Παρίσι, φτιαγμένη στην Τοσκάνη. Αγορά στο κατάστημά τους.",
    shopsMiscianoLink: "Συνεργάτης · Αγόρασε απευθείας από Misciano Paris",
    miscianoText: "Φίρμα-συνεργάτης. Γυναικεία ένδυση σχεδιασμένη στο Παρίσι, φτιαγμένη στην Τοσκάνη — φορέματα, έτοιμα ενδύματα και αξεσουάρ σε ήσυχη, ρευστή γραμμή. Αγορά στο δικό τους κατάστημα.",
    mDraped: "Ντραπέ φόρεμα από μπεζ κρεπ με λαιμόκοψη σε αντίθεση",
    mCowlLong: "Μακρύ μαύρο φόρεμα με βαθύ ντραπέ λαιμό και κορδόνια",
    mSageSatin: "Σατέν μίντι φόρεμα σε πράσινο φασκόμηλο με ντραπέ λαιμό",
    mRibKnit: "Μαύρο μίντι φόρεμα από ριπ πλέξη",
    mCrepe: "Κρεπ",
    mEvening: "Βραδινό",
    mSatin: "Σατέν",
    mKnit: "Πλεκτό",
    mChampagne: "Μίντι φόρεμα σε χρώμα σαμπάνιας με πέρλες και παγιέτες",
    mAsymLong: "Μακρύ μαύρο φόρεμα με ασύμμετρη λαιμόκοψη",
    mPleatedPink: "Μακρύ πλισέ φόρεμα από μουσελίνα σε ροζ πούδρας",
    mGreenCorset: "Μακρύ πράσινο βραδινό φόρεμα με κεντημένο κορσέ",
    mSequins: "Παγιέτες",
    mChiffon: "Μουσελίνα",
    mTulle: "Τούλι",
    shopErverte: "Συνεργάτης · Αγόρασε απευθείας από Erverte Paris",
    shopViaduct: "Συνεργάτης · Αγόρασε απευθείας από Viaduct Clothing",
    shopTalbot: "Συνεργάτης · Αγόρασε απευθείας από Talbot Runhof",
    openEdit: "Δες την επιλογή",
    talbotBlurb: "Γερμανία. Βραδινά και επίσημα γυναικεία, Μόναχο. Αγορά στο κατάστημά τους.",
    also: "Επίσης",
    shopTheirStore: "Ψώνισε στο κατάστημά τους",
    lookEyebrow: "Επιλογή ήσυχης πολυτέλειας",
    lookTitle: "Δημιούργησε το σύνολο",
    lookSub: "Ήσυχη πολυτέλεια, σε τρεις κινήσεις.",
    lookName1: "Σακάκι Rush3",
    lookName2: "Λευκό βαμβακερό μπλουζάκι – Γαλλική κατασκευή",
    lookName3: "Γυναικεία παπούτσια adidas Originals Court Tourino – Λευκό",
    lookPrice3: "£54.99 (αρχική τιμή £75.00)",
    buy: "Αγορά",
    affLinks: "Σύνδεσμοι συνεργατών.",
    shopsTitle: "Καταστήματα συνεργατών",
    shopsText: "Μόνο οίκοι ενεργοί στη Glamour. Οι συνεργασίες σε εκκρεμότητα δεν εμφανίζονται.",
    shopsErverte: "Γαλλία. Ανδρικά σε φυσικές ίνες, γαλλικής κατασκευής. Αγορά στο κατάστημά τους.",
    shopsErverteLink: "Συνεργάτης · Αγόρασε απευθείας από Erverte Paris",
    shopsViaduct: "Ηνωμένο Βασίλειο. Αθλητικά παπούτσια και σπορ. Αγορά στο κατάστημά τους.",
    shopsViaductLink: "Συνεργάτης · Αγόρασε απευθείας από Viaduct Clothing",
    shopsTalbotLink: "Συνεργάτης · Αγόρασε απευθείας από Talbot Runhof",
    nextTitle: "Επόμενοι οίκοι",
    nextText: "Ευρωπαϊκοί οίκοι εμφανίζονται εδώ μόλις εγκριθεί η συνεργασία.",
    seeAll: "Δες όλα",
    showLess: "Λιγότερα",
    onStore: "Αγορά στο κατάστημά τους",
    ctaErverte: "Συνεργάτης · Αγόρασε απευθείας από Erverte Paris",
    ctaViaduct: "Συνεργάτης · Αγόρασε απευθείας από Viaduct Clothing",
    ctaTalbot: "Συνεργάτης · Αγόρασε απευθείας από Talbot Runhof",
    ctaMisciano: "Συνεργάτης · Αγόρασε απευθείας από Misciano Paris",
    talbotText: "Γερμανία · βραδινά και επίσημα γυναικεία, Μόναχο. Συνεργάτης — αγορά στο κατάστημά τους.",
    nSommerhit2: "Βραδινό φόρεμα Sommerhit2",
    nSolite1: "Βραδινό φόρεμα Solite1",
    nKortney1: "Φόρεμα κοκτέιλ Kortney1",
    nSocialclub6: "Βραδινό φόρεμα Socialclub6",
    nMobina2: "Βραδινό φόρεμα Mobina2",
    nSodium2: "Βραδινό φόρεμα Sodium2",
    nSocialclub3: "Βραδινό φόρεμα Socialclub3",
    nTolga12: "Βραδινό φόρεμα Tolga12",
    seeAllTalbot: "Δες όλα τα Talbot στο κατάστημα",
    shopAllTalbot: "Συνεργάτης · Αγόρασε απευθείας από Talbot Runhof",
    lbAlt1: "NATALLIA CUT · ιβουάρ τοίχος · ολόκληρο το σύνολο",
    lbAlt2: "NATALLIA CUT · Μαρίνα Λεμεσού · ολόκληρο το σύνολο",
    lbAlt3: "NATALLIA CUT · τερακότα και φασκόμηλο · ολόκληρο το σύνολο",
    lbDots1: "Διαφάνειες λευκώματος",
    lbTitle1: "NATALLIA CUT · Λεμεσός",
    lbText1: "Ήσυχη πολυτέλεια. Εκδοτική ματιά.",
    lbAlt4: "Natallia Cut · Βράδυ · Λεμεσός · μαύρο, λαιμόκοψη βάρκα",
    lbAlt5: "Natallia Cut · Βράδυ · Λεμεσός · κόκκινο φόρεμα",
    lbAlt6: "Natallia Cut · Βράδυ · Λεμεσός · σκούρο μπλε φόρεμα",
    lbDots2: "Διαφάνειες Natallia Cut · Βράδυ",
    lbTitle2: "Natallia Cut · Βράδυ · Λεμεσός",
    lbCta: "Συνεργάτης · Αγορά απευθείας από την Talbot Runhof",
    lbAlt7: "RODOULA CUT · Βράδυ · ιβουάρ σατέν",
    lbAlt8: "RODOULA CUT · Βράδυ · ιβουάρ σατέν με όγκο",
    lbAlt9: "RODOULA CUT · Βράδυ · σκούρο μπλε, με έναν ώμο",
    lbAlt10: "RODOULA CUT · Βράδυ · κόκκινο στράπλες, γραμμή γοργόνα",
    lbAlt11: "RODOULA CUT · Βράδυ · μαύρο κρουαζέ, μαρίνα",
    lbDots3: "Διαφάνειες Rodoula · Βράδυ",
    lbTitle3: "RODOULA CUT · Βράδυ",
    lbText3: "Φως Μονάχου. Λεμεσός.",
    slide: "Διαφάνεια",
    viaductText: "Φίρμα-συνεργάτης. Άνδρες, γυναίκες, αθλητικά παπούτσια. Αγορά στο δικό τους κατάστημα.",
    whiteBlue: "Λευκό / Μπλε",
    vAltWhite: "Nike Tech Windrunner λευκό",
    vAltTartan: "Καρό μπουφάν adidas Tartan",
    vTartan: "Μπουφάν adidas Tartan",
    vAltShorts: "Σορτς adidas",
    vShorts: "Σορτς adidas Climacool",
    vTisch: "Παπούτσια adidas Tischtennis",
    vAltTisch: "Μαύρα αθλητικά παπούτσια adidas Originals Tischtennis",
    vNatTennis: "Παπούτσια adidas National Tennis",
    vAltNatTennis: "Λευκά παπούτσια adidas Originals National Tennis OG",
    vCoach: "Κοτλέ μπουφάν adidas",
    vAltCoach: "Καφέ κοτλέ μπουφάν adidas Originals Coach",
    vPuffer: "Πουπουλένιο μπουφάν adidas",
    vAltPuffer: "Μαύρο πουπουλένιο μπουφάν adidas Essentials",
    newIn: "Νέες αφίξεις",
    newInText: "Η πιο πρόσφατη συλλογή της Viaduct.",
    openNewIn: "Δες τις νέες αφίξεις",
    menText: "Μπουφάν, φούτερ, σπορ.",
    openMen: "Δες τα ανδρικά",
    womenText: "Γυναικεία ένδυση και αθλητικά παπούτσια.",
    openWomen: "Δες τα γυναικεία",
    footwear: "Υποδήματα",
    openFootwear: "Δες τα υποδήματα",
    shopAllViaduct: "Συνεργάτης · Αγόρασε απευθείας από Viaduct Clothing",
    erverteText: "Φίρμα-συνεργάτης. Κορυφαία ανδρικά σε φυσικές ίνες, γαλλικής κατασκευής. Αγορά στο δικό τους κατάστημα.",
    eGeo: "Λινό πουκάμισο Geometric Harmony",
    madeInFrance: "Γαλλική κατασκευή",
    eGreyHoodie: "Γκρι φούτερ με κουκούλα",
    organicCotton: "Οργανικό βαμβάκι",
    eAltPolo: "Σκούρο μπλε πόλο",
    ePolo: "Σκούρο μπλε οργανικό πόλο",
    eAltTee: "Σκούρο μπλε μπλουζάκι",
    eTee: "Σκούρο μπλε βαμβακερό μπλουζάκι",
    eLinenOversized: "Φαρδύ λινό πουκάμισο",
    eAltLinenOversized: "Φαρδύ λινό πουκάμισο",
    eLinenTee: "Μπλουζάκι από οργανικό γαλλικό λινό",
    eAltLinenTee: "Λινό μπλουζάκι",
    eLinenShorts: "Λινό σορτς",
    eAltLinenShorts: "Λινό σορτς",
    linen100: "100% λινό",
    eAllText: "Ολόκληρη η συλλογή Erverte.",
    openAll: "Δες όλα",
    eShirtsText: "Λινά και μεταξωτά πουκάμισα.",
    openShirts: "Δες τα πουκάμισα",
    theHouse: "Ο οίκος",
    theHouseText: "Φυσικές ίνες, γαλλική κατασκευή.",
    aboutErverte: "Σχετικά με την Erverte",
    shopAllErverte: "Συνεργάτης · Αγόρασε απευθείας από Erverte Paris",
    sizesTitle: "Οδηγός μεγεθών ΕΕ · Κύπρος & ΕΕ",
    sizesText: "Τα κομμάτια του οίκου ακολουθούν την ευρωπαϊκή αρίθμηση. Τα καταστήματα συνεργατών έχουν τον δικό τους πίνακα στην ολοκλήρωση της αγοράς.",
    limassol: "Λεμεσός",
    oneSite: "Ένας ιστότοπος, δύο γλώσσες.",
    tluxyText: "Ευρωπαϊκό κατάστημα πολλών οίκων",
    tluxyAlt: "Λογότυπο T.LUXY",
    pitodText: "Βιώσιμη μόδα · Βασικά ρούχα για όλους από οργανικό βαμβάκι",
    pitodAlt: "Φούτερ με κουκούλα Pitod από οργανικό βαμβάκι",
    alvieroText: "Ιταλική κληρονομιά · Χαρακτηριστικές τσάντες και αξεσουάρ με τύπωμα χάρτη",
    alvieroAlt: "Μακρόστενη τσάντα ώμου Alviero Martini με τύπωμα χάρτη",
    coesText: "Ανεξάρτητο βρετανικό κατάστημα από το 1928 · Ρούχα, υποδήματα και αθλητική ένδυση",
    coesAlt: "Coes – ρούχα, υποδήματα και αθλητική ένδυση",
    openStore: "Επίσκεψη στο κατάστημα",
    footPlace: "Λεμεσός · Κύπρος",
    shopsLink: "Καταστήματα",
    sizesLink: "Μεγέθη",
    contactH: "Επικοινωνία",
    followH: "Ακολούθησέ μας",
    audioPlay: "Αναπαραγωγή",
    audioMute: "Σίγαση",
    audioHint: "κλικ για αναπαραγωγή/παύση · διπλό κλικ για το επόμενο",
    /* Legal baseline 2026-10-02: cookie banner, footer legal links, /privacy /cookies /terms /imprint */
    lgPrivacy: "Απόρρητο", lgCookies: "Cookies", lgTerms: "Όροι", lgImprint: "Στοιχεία", lgCookieSettings: "Ρυθμίσεις cookies",
    ckLabel: "Συναίνεση για cookies",
    ckText: "Χρησιμοποιούμε απαραίτητα cookies για τη λειτουργία του site. Τα προαιρετικά cookies (analytics, affiliate) φορτώνουν μόνο αν τα αποδεχτείς.",
    ckAccept: "Αποδοχή", ckReject: "Απόρριψη προαιρετικών", ckSettings: "Ρυθμίσεις", ckSave: "Αποθήκευση",
    ckEssential: "Απαραίτητα", ckEssentialD: "Γλώσσα και επιλογή cookies. Πάντα ενεργά.",
    ckAnalytics: "Analytics", ckAnalyticsD: "Στατιστικά επισκέψεων. Ανενεργά, εκτός αν τα ενεργοποιήσεις.",
    ckAffiliate: "Affiliate", ckAffiliateD: "Μέτρηση κλικ μέσω Awin για τα καταστήματα συνεργατών. Ανενεργά, εκτός αν τα ενεργοποιήσεις.",
    lastUpdated: "Τελευταία ενημέρωση: 2 Οκτωβρίου 2026",
    backHome: "← Επιστροφή στη Glamour",
    pvDocTitle: "Πολιτική απορρήτου — Glamour",
    pvMeta: "Πώς η Glamour (www.glamourcy.com) χειρίζεται τα προσωπικά δεδομένα: τι συλλέγουμε, γιατί, πού διαβιβάζονται, τα δικαιώματά σου βάσει GDPR και πόσο τα διατηρούμε.",
    pvTitle: "Πολιτική απορρήτου",
    pvIntro: "Εδώ εξηγούμε ποια προσωπικά δεδομένα επεξεργάζεται το www.glamourcy.com, για ποιο σκοπό και ποια είναι τα δικαιώματά σου.",
    pvCtrlH: "Υπεύθυνος επεξεργασίας",
    pvCtrl: "Marinos Protopapas, Glamour, Λεμεσός, Κύπρος.",
    emailLabel: "Email:",
    pvCollectH: "Τι συλλέγουμε",
    pvC1: "Τη διεύθυνση email και το μήνυμά σου, αν μας γράψεις.",
    pvC2: "Τεχνικά αρχεία καταγραφής που τηρεί ο πάροχος φιλοξενίας όταν επισκέπτεσαι το site (για παράδειγμα διεύθυνση IP, τύπος προγράμματος περιήγησης και ώρα του αιτήματος).",
    pvC3: "Την επιλογή σου για τα cookies, αποθηκευμένη στο πρόγραμμα περιήγησής σου.",
    pvWhyH: "Για ποιο σκοπό",
    pvW1: "Για τη λειτουργία του site.",
    pvW2: "Για να απαντάμε στα μηνύματά σου.",
    pvW3: "Για τη μέτρηση των συνδέσμων συνεργατών (affiliate), μόνο αφού πατήσεις «Αποδοχή».",
    pvWhereH: "Πού διαβιβάζονται τα δεδομένα",
    pvP1: "Vercel — φιλοξενία του site.",
    pvP2: "Awin — καταγραφή κλικ σε συνδέσμους συνεργατών, μόνο αν πατήσεις «Αγορά» και συνεχίσεις στο κατάστημα κάποιου συνεργάτη.",
    pvNoSellH: "Τι δεν κάνουμε",
    pvNoSell: "Δεν πουλάμε τα δεδομένα σου. Δεν έχουμε δικό μας σύστημα αγορών: κάθε αγορά γίνεται στον ιστότοπο του οίκου-συνεργάτη.",
    pvRightsH: "Τα δικαιώματά σου (GDPR)",
    pvRights: "Μπορείς να ζητήσεις πρόσβαση, διόρθωση ή διαγραφή των προσωπικών σου δεδομένων, γράφοντάς μας στο παραπάνω email. Έχεις επίσης δικαίωμα να υποβάλεις καταγγελία στον Επίτροπο Προστασίας Δεδομένων Προσωπικού Χαρακτήρα της Κύπρου.",
    pvRetH: "Πόσο διατηρούμε τα δεδομένα",
    pvR1: "Τεχνικά αρχεία καταγραφής: για όσο διάστημα απαιτεί ο πάροχος φιλοξενίας.",
    pvR2: "Μηνύματα: μέχρι να κλείσει το θέμα.",
    pvR3: "Επιλογή cookies: στο πρόγραμμα περιήγησής σου, μέχρι να την αλλάξεις ή να τη διαγράψεις.",
    pvMoreCookies: "Δες την πολιτική cookies",
    cpDocTitle: "Πολιτική cookies — Glamour",
    cpMeta: "Ποια cookies χρησιμοποιεί η Glamour (www.glamourcy.com): απαραίτητη αποθήκευση γλώσσας και επιλογής, και προαιρετικά cookies affiliate και analytics μόνο αφού τα αποδεχτείς.",
    cpTitle: "Πολιτική cookies",
    cpIntro: "Το site χρησιμοποιεί cookies και παρόμοιες τεχνολογίες αποθήκευσης στο πρόγραμμα περιήγησης. Τα απαραίτητα είναι πάντα ενεργά· τα προαιρετικά φορτώνουν μόνο αφού τα αποδεχτείς.",
    cpEssH: "Απαραίτητα (πάντα ενεργά)",
    cpEss: "Η γλώσσα σου (EN/EL) και η επιλογή σου για τα cookies. Αποθηκεύονται στο πρόγραμμα περιήγησής σου και χρειάζονται για να λειτουργεί το site.",
    cpOptH: "Προαιρετικά (μόνο μετά την «Αποδοχή»)",
    cpOpt1: "Affiliate: cookies της Awin για τα κλικ, ώστε το κατάστημα του συνεργάτη να αναγνωρίζει ότι η αγορά έγινε μέσω της Glamour.",
    cpOpt2: "Analytics: στατιστικά επισκέψεων. Αυτή τη στιγμή δεν λειτουργεί κανένα εργαλείο analytics στο site· αν προστεθεί, θα φορτώνει μόνο αφού το αποδεχτείς.",
    cpChangeH: "Πώς αλλάζεις την επιλογή σου",
    cpChange: "Πάτησε το κουμπί «Ρυθμίσεις cookies» στο κάτω μέρος οποιασδήποτε σελίδας. Ανοίγει ξανά τις ρυθμίσεις, ώστε να αλλάξεις την επιλογή σου όποτε θέλεις.",
    cpOpen: "Άνοιγμα ρυθμίσεων cookies",
    tmDocTitle: "Όροι χρήσης — Glamour",
    tmMeta: "Όροι χρήσης της Glamour (www.glamourcy.com): επιμελημένη επιλογή, όχι κατάστημα. Αγορά, πληρωμή, αποστολή και επιστροφές γίνονται στον ιστότοπο κάθε οίκου.",
    tmTitle: "Όροι χρήσης",
    tm1H: "Επιλογή, όχι κατάστημα",
    tm1: "Η Glamour είναι μια επιμελημένη επιλογή, όχι κατάστημα. Παρουσιάζουμε επιλεγμένα κομμάτια από οίκους-συνεργάτες.",
    tm2H: "Αγορές",
    tm2: "Η αγορά, η πληρωμή, η αποστολή, οι επιστροφές και τα μεγέθη γίνονται στον ιστότοπο του ίδιου του οίκου, σύμφωνα με τους δικούς του όρους.",
    tm3H: "Τιμές",
    tm3: "Οι τιμές μπορεί να αλλάξουν στον ιστότοπο του οίκου. Ισχύει η τιμή που εμφανίζεται εκεί κατά την ολοκλήρωση της αγοράς.",
    tm4H: "Σύνδεσμοι συνεργατών",
    tm4: "Λαμβάνουμε προμήθεια αν αγοράσεις μέσω συνδέσμου συνεργάτη (affiliate). Η τιμή για σένα δεν αλλάζει.",
    tm5H: "Φωτογραφίες",
    tm5: "Οι φωτογραφίες του Lookbook είναι editorial. Το προϊόν που αγοράζεις είναι αυτό που εμφανίζεται στο κατάστημα του οίκου.",
    tmContactH: "Ερωτήσεις",
    imDocTitle: "Στοιχεία — Glamour",
    imMeta: "Στοιχεία της Glamour (www.glamourcy.com): Marinos Protopapas, Λεμεσός, Κύπρος. Επικοινωνία μέσω email.",
    imTitle: "Στοιχεία",
    imName: "Όνομα", imBrand: "Brand", imPlace: "Τοποθεσία", imPlaceV: "Λεμεσός, Κύπρος", imEmail: "Email", imWeb: "Ιστότοπος",
    rec: { coast: "Λινό.", city: "Ραπτική.", night: "Βράδυ.", knit: "Πλεκτό." }
  }
};

