const PRODUCTS = [
  { id:"m1", brand:"glamour", cat:"men", type:"shirts", price:145, img:"https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=900&q=80", en:{name:"Coastal Linen Shirt",desc:"Stone linen."}, el:{name:"Λινό Coastal",desc:"Λινό πέτρας."} },
  { id:"m2", brand:"glamour", cat:"men", type:"tailoring", price:390, img:"https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?auto=format&fit=crop&w=900&q=80", en:{name:"Ink Blazer",desc:"Unstructured."}, el:{name:"Σακάκι Ink",desc:"Μαλακός ώμος."} },
  { id:"m3", brand:"mare", cat:"men", type:"tailoring", price:220, img:"https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80", en:{name:"Crete Trouser",desc:"High rise."}, el:{name:"Παντελόνι Crete",desc:"Ψηλή μέση."} },
  { id:"m4", brand:"mare", cat:"men", type:"knit", price:180, img:"https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=900&q=80", en:{name:"Cashmere Crew",desc:"Ivory knit."}, el:{name:"Πλεκτό Cashmere",desc:"Εκρού."} },
  { id:"m5", brand:"glamour", cat:"men", type:"shirts", price:155, img:"https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=900&q=80", en:{name:"Marina Oxford",desc:"White oxford."}, el:{name:"Oxford Marina",desc:"Λευκό oxford."} },
  { id:"m6", brand:"glamour", cat:"men", type:"tailoring", price:245, img:"https://images.unsplash.com/photo-1488161628813-04466f872be2?auto=format&fit=crop&w=900&q=80", en:{name:"Harbour Chino",desc:"Stone cotton."}, el:{name:"Chino Harbour",desc:"Βαμβάκι πέτρας."} },
  { id:"m7", brand:"mare", cat:"men", type:"knit", price:210, img:"https://images.unsplash.com/photo-1516826957135-700dedea698c?auto=format&fit=crop&w=900&q=80", en:{name:"Navy Polo Knit",desc:"Fine polo."}, el:{name:"Polo Navy",desc:"Polo."} },
  { id:"m8", brand:"glamour", cat:"men", type:"shirts", price:175, img:"https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=900&q=80", en:{name:"Sand Overshirt",desc:"Marina jacket-shirt."}, el:{name:"Overshirt Sand",desc:"Πουκάμισο-σακάκι."} },
  { id:"m9", brand:"mare", cat:"men", type:"tailoring", price:420, img:"https://images.unsplash.com/photo-1488161628813-04466f872be2?auto=format&fit=crop&w=900&q=80", en:{name:"Navy Dinner Jacket",desc:"Evening jacket."}, el:{name:"Σακάκι Dinner",desc:"Βραδινό."} },
  { id:"m10", brand:"glamour", cat:"men", type:"shirts", price:135, img:"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80", en:{name:"Black Poplin Shirt",desc:"Day to night."}, el:{name:"Μαύρο Poplin",desc:"Μαύρο πουκάμισο."} },
  { id:"m11", brand:"glamour", cat:"men", type:"tailoring", price:280, img:"https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?auto=format&fit=crop&w=900&q=80", en:{name:"Stone Suit Trouser",desc:"Clean crease."}, el:{name:"Παντελόνι Stone",desc:"Καθαρή γραμμή."} },
  { id:"m12", brand:"mare", cat:"men", type:"knit", price:165, img:"https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80", en:{name:"Ivory Rollneck",desc:"Fine merino."}, el:{name:"Ζιβάγκο Ivory",desc:"Merino."} },
  { id:"m13", brand:"glamour", cat:"men", type:"shirts", price:149, img:"https://images.unsplash.com/photo-1516826957135-700dedea698c?auto=format&fit=crop&w=900&q=80", en:{name:"Open Collar Linen",desc:"Heat ready."}, el:{name:"Λινό ανοιχτό",desc:"Χωρίς γραβάτα."} },
  { id:"m14", brand:"mare", cat:"men", type:"tailoring", price:455, img:"https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?auto=format&fit=crop&w=900&q=80", en:{name:"Charcoal Suit Jacket",desc:"Soft construction."}, el:{name:"Σακάκι Charcoal",desc:"Μαλακή κατασκευή."} },
  { id:"m15", brand:"glamour", cat:"men", type:"knit", price:195, img:"https://images.unsplash.com/photo-1488161628813-04466f872be2?auto=format&fit=crop&w=900&q=80", en:{name:"Sand Knit Polo",desc:"Resort polo."}, el:{name:"Polo Sand",desc:"Polo παραλίας."} },
  { id:"m16", brand:"glamour", cat:"men", type:"shirts", price:168, img:"https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=900&q=80", en:{name:"Stripe Marina Shirt",desc:"Blue stripe."}, el:{name:"Ριγέ Marina",desc:"Ρίγα."} },
  { id:"m17", brand:"mare", cat:"men", type:"tailoring", price:235, img:"https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=900&q=80", en:{name:"Olive Drawstring",desc:"Tailored ease."}, el:{name:"Olive Drawstring",desc:"Άνεση."} },
  { id:"m18", brand:"glamour", cat:"men", type:"knit", price:225, img:"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80", en:{name:"Bone Sweater",desc:"Weekend knit."}, el:{name:"Πουλόβερ Bone",desc:"Σαββατοκύριακο."} },
  { id:"m19", brand:"glamour", cat:"men", type:"tailoring", price:365, img:"https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?auto=format&fit=crop&w=900&q=80", en:{name:"Camel Unstructured",desc:"Light jacket."}, el:{name:"Σακάκι Camel",desc:"Ελαφρύ σακάκι."} },
  { id:"m20", brand:"mare", cat:"men", type:"shirts", price:188, img:"https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=900&q=80", en:{name:"White Dinner Shirt",desc:"Evening shirt."}, el:{name:"Πουκάμισο Dinner",desc:"Βραδινό."} },
  { id:"m21", brand:"glamour", cat:"men", type:"tailoring", price:210, img:"https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80", en:{name:"Navy Chino",desc:"Everyday navy."}, el:{name:"Chino Navy",desc:"Navy."} },
  { id:"m22", brand:"glamour", cat:"men", type:"knit", price:175, img:"https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?auto=format&fit=crop&w=900&q=80", en:{name:"Clay Cardigan",desc:"Open knit."}, el:{name:"Ζακέτα Clay",desc:"Ανοιχτό πλεκτό."} },
  { id:"m23", brand:"mare", cat:"men", type:"shirts", price:142, img:"https://images.unsplash.com/photo-1516826957135-700dedea698c?auto=format&fit=crop&w=900&q=80", en:{name:"Short Sleeve Linen",desc:"High summer."}, el:{name:"Κοντομάνικο λινό",desc:"Καλοκαίρι."} },
  { id:"m24", brand:"glamour", cat:"men", type:"tailoring", price:490, img:"https://images.unsplash.com/photo-1488161628813-04466f872be2?auto=format&fit=crop&w=900&q=80", en:{name:"Ivory Dinner Suit",desc:"Evening."}, el:{name:"Κουστούμι Ivory",desc:"Βραδινό."} },
  { id:"w1", brand:"nisi", cat:"women", type:"dresses", price:260, img:"https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=900&q=80", en:{name:"Ivory Slip Dress",desc:"Bias silk."}, el:{name:"Ivory Slip",desc:"Μετάξι."} },
  { id:"w2", brand:"glamour", cat:"women", type:"shirts", price:165, img:"https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80", en:{name:"Midnight Shirt",desc:"Black poplin."}, el:{name:"Midnight Shirt",desc:"Μαύρο poplin."} },
  { id:"w3", brand:"nisi", cat:"women", type:"dresses", price:310, img:"https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=80", en:{name:"Aegean Column",desc:"Long dress."}, el:{name:"Στήλη Aegean",desc:"Μακρύ φόρεμα."} },
  { id:"w4", brand:"nisi", cat:"women", type:"knit", price:195, img:"https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=900&q=80", en:{name:"Soft Culotte Knit",desc:"Wide knit."}, el:{name:"Culotte",desc:"Πλεκτό παντελόνι."} },
  { id:"w5", brand:"glamour", cat:"women", type:"shirts", price:170, img:"https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=80", en:{name:"Ivory Silk Shirt",desc:"Open collar."}, el:{name:"Μεταξωτό Ivory",desc:"Ανοιχτός γιακάς."} },
  { id:"w6", brand:"nisi", cat:"women", type:"dresses", price:285, img:"https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=900&q=80", en:{name:"Limassol Wrap",desc:"Warm wrap."}, el:{name:"Wrap Λεμεσός",desc:"Wrap."} },
  { id:"w7", brand:"glamour", cat:"women", type:"tailoring", price:340, img:"https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&w=900&q=80", en:{name:"Camel Coat Dress",desc:"Light tailoring."}, el:{name:"Παλτό Camel",desc:"Ραπτική."} },
  { id:"w8", brand:"nisi", cat:"women", type:"knit", price:205, img:"https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=900&q=80", en:{name:"Bone Cardigan",desc:"Long knit."}, el:{name:"Ζακέτα Bone",desc:"Μακρύ πλεκτό."} },
  { id:"w9", brand:"glamour", cat:"women", type:"shirts", price:160, img:"https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=900&q=80", en:{name:"Black Column Blouse",desc:"Sharp cuff."}, el:{name:"Μπλούζα Column",desc:"Μανίκι."} },
  { id:"w10", brand:"nisi", cat:"women", type:"dresses", price:295, img:"https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&w=900&q=80", en:{name:"Rose Column",desc:"Long dress."}, el:{name:"Στήλη Rose",desc:"Μακρύ φόρεμα."} },
  { id:"w11", brand:"glamour", cat:"women", type:"dresses", price:275, img:"https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=900&q=80", en:{name:"Black Slip",desc:"Evening bias."}, el:{name:"Μαύρο Slip",desc:"Βραδινό."} },
  { id:"w12", brand:"nisi", cat:"women", type:"shirts", price:155, img:"https://images.unsplash.com/photo-1558611848-73f7eb4001a1?auto=format&fit=crop&w=900&q=80", en:{name:"Sand Tunic Shirt",desc:"Long line."}, el:{name:"Τουνίκ Sand",desc:"Μακριά γραμμή."} },
  { id:"w13", brand:"glamour", cat:"women", type:"knit", price:188, img:"https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80", en:{name:"Ivory Fine Knit",desc:"Fine knit."}, el:{name:"Λεπτό Ivory",desc:"Πλεκτό."} },
  { id:"w14", brand:"nisi", cat:"women", type:"dresses", price:330, img:"https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=900&q=80", en:{name:"Gallery Dress",desc:"City night."}, el:{name:"Φόρεμα Gallery",desc:"Νύχτα πόλης."} },
  { id:"w15", brand:"glamour", cat:"women", type:"tailoring", price:365, img:"https://images.unsplash.com/photo-1562157873-818bc0726f68?auto=format&fit=crop&w=900&q=80", en:{name:"Stone Tailored Coat",desc:"Light coat."}, el:{name:"Παλτό Stone",desc:"Ελαφρύ παλτό."} },
  { id:"w16", brand:"nisi", cat:"women", type:"dresses", price:245, img:"https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=900&q=80", en:{name:"Cotton Day Dress",desc:"Marina day."}, el:{name:"Φόρεμα ημέρας",desc:"Μαρίνα."} },
  { id:"w17", brand:"glamour", cat:"women", type:"shirts", price:175, img:"https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80", en:{name:"White Open Shirt",desc:"Over the slip."}, el:{name:"Άσπρο ανοιχτό",desc:"Πάνω από slip."} },
  { id:"w18", brand:"nisi", cat:"women", type:"knit", price:215, img:"https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=900&q=80", en:{name:"Black Long Knit",desc:"Column knit."}, el:{name:"Μαύρο πλεκτό",desc:"Στήλη."} },
  { id:"w19", brand:"glamour", cat:"women", type:"dresses", price:355, img:"https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=900&q=80", en:{name:"Gold Hour Gown",desc:"Evening length."}, el:{name:"Βραδινό Gold Hour",desc:"Βράδυ."} },
  { id:"w20", brand:"nisi", cat:"women", type:"tailoring", price:290, img:"https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=900&q=80", en:{name:"Ivory Trouser",desc:"Wide pressed."}, el:{name:"Παντελόνι Ivory",desc:"Φαρδύ."} },
  { id:"w21", brand:"glamour", cat:"women", type:"shirts", price:148, img:"https://images.unsplash.com/photo-1558611848-73f7eb4001a1?auto=format&fit=crop&w=900&q=80", en:{name:"Linen Camp Shirt",desc:"Heat and salt."}, el:{name:"Λινό Camp",desc:"Ζέστη."} },
  { id:"w22", brand:"nisi", cat:"women", type:"dresses", price:268, img:"https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=900&q=80", en:{name:"Terra Wrap",desc:"Clay wrap."}, el:{name:"Wrap Terra",desc:"Wrap."} },
  { id:"w23", brand:"glamour", cat:"women", type:"knit", price:198, img:"https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&w=900&q=80", en:{name:"Blush Crew",desc:"Soft crew."}, el:{name:"Πλεκτό Blush",desc:"Μαλακό."} },
  { id:"w24", brand:"nisi", cat:"women", type:"dresses", price:399, img:"https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=900&q=80", en:{name:"Midnight Column",desc:"Black evening."}, el:{name:"Στήλη Midnight",desc:"Μαύρη βραδινή."} }
];
let lang=localStorage.getItem("glamour-lang")||"en"; let filter="all"; let cart=JSON.parse(localStorage.getItem("glamour-cart")||"[]"); let activeProduct=null; let activeSize="M";
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function t(key){let v=I18N[lang]; for(const p of key.split(".")) v=v?.[p]; return v??key;}
function applyLang(){$$("[data-i]").forEach(el=>el.textContent=t(el.dataset.i)); $$("[data-ph]").forEach(el=>el.placeholder=t(el.dataset.ph)); document.documentElement.lang=lang==="el"?"el":"en"; $$(".lang-btn").forEach(b=>b.classList.toggle("active",b.dataset.lang===lang)); renderProducts(); renderBrands(); renderCart();}
function brandOf(p){return BRANDS.find(b=>b.id===(p.brand||"glamour"));}
function renderBrands(){const root=document.getElementById("brands"); if(!root)return; root.innerHTML=BRANDS.map(b=>`<article class="brand-card" onclick="setFilter('${b.id}', null)"><h3>${b.name}</h3><p>${b[lang]}</p><div class="comm">${b.model==="own"?(lang==="el"?"Οίκος · 100%":"House · 100%"):(lang==="el"?"Προμήθεια ":"Commission ")+b.cut+"%"}</div></article>`).join("");}
function renderProducts(){const root=$("#grid"); if(!root)return; const list=PRODUCTS.filter(p=>filter==="all"||p.cat===filter||p.type===filter||p.brand===filter); root.innerHTML=list.map(p=>`<article class="card" onclick="openProduct('${p.id}')"><div class="card-img"><span class="badge">${p.cat==="men"?t("men"):t("women")}</span><img src="${p.img}" alt="${p[lang].name}"></div><div class="card-body"><h3>${p[lang].name}</h3><div class="meta"><span>${brandOf(p).name}</span><strong>€${p.price}</strong></div></div></article>`).join("");}
function openProduct(id){activeProduct=PRODUCTS.find(p=>p.id===id); activeSize="M"; $("#drawer").style.display="block"; const b=brandOf(activeProduct); $("#drawer-body").innerHTML=`<button class="icon-btn" onclick="closeDrawer()">${t("close")}</button><div class="product-hero"><img src="${activeProduct.img}" alt=""></div><h2>${activeProduct[lang].name}</h2><p style="color:var(--muted);margin:8px 0 16px">${activeProduct[lang].desc}</p><p>${t("soldBy")} <strong>${b.name}</strong></p><strong>€${activeProduct.price}</strong><p style="margin-top:16px">${t("size")}</p><div class="sizes">${["XS","S","M","L","XL"].map(s=>`<button class="${s===activeSize?"active":""}" onclick="setSize('${s}', this)">${s}</button>`).join("")}</div><button class="cta" style="width:100%;margin-top:8px" onclick="addToCart()">${t("add")}</button>`;}
function setSize(s,el){activeSize=s; $$(".sizes button").forEach(b=>b.classList.remove("active")); el.classList.add("active");}
function closeDrawer(){$("#drawer").style.display="none";} function closeCart(){$("#cart").style.display="none";} function openCart(){renderCart(); $("#cart").style.display="block";}
function addToCart(){cart.push({id:activeProduct.id,size:activeSize,qty:1}); localStorage.setItem("glamour-cart",JSON.stringify(cart)); updateCount(); closeDrawer();}
function renderCart(){const body=$("#cart-body"); if(!body)return; if(!cart.length){body.innerHTML=`<p>${t("empty")}</p>`; $("#cart-total").textContent="€0"; return;} let total=0; body.innerHTML=cart.map(item=>{const p=PRODUCTS.find(x=>x.id===item.id); total+=p.price; return `<div class="cart-item"><img src="${p.img}" alt=""><div><strong>${p[lang].name}</strong><div>${item.size}</div></div><div>€${p.price}</div></div>`;}).join(""); $("#cart-total").textContent="€"+total;}
function updateCount(){const c=$("#count"); if(c)c.textContent=cart.length;} function setLang(next){lang=next; localStorage.setItem("glamour-lang",lang); applyLang();} function setFilter(next,el){filter=next; $$(".chip").forEach(c=>c.classList.remove("active")); if(el)el.classList.add("active"); renderProducts(); document.getElementById("shop")?.scrollIntoView({behavior:"smooth"});}
function partnerApply(e){e.preventDefault(); e.target.reset(); alert(lang==="el"?"Η αίτηση καταγράφηκε ως demo.":"Application saved as demo.");}
function quiz(mood){const box=$("#quiz-result"); box.style.display="block"; box.textContent=I18N[lang].rec[mood];}
function newsletter(e){e.preventDefault(); e.target.reset(); alert(lang==="el"?"Ευχαριστούμε.":"Thank you.");}
window.openProduct=openProduct; window.setSize=setSize; window.closeDrawer=closeDrawer; window.closeCart=closeCart; window.openCart=openCart; window.addToCart=addToCart; window.setLang=setLang; window.setFilter=setFilter; window.quiz=quiz; window.newsletter=newsletter; window.partnerApply=partnerApply;
applyLang(); updateCount();
