const PRODUCTS = [
  { id:"m1", brand:"glamour", cat:"men", type:"shirts", price:145, img:"https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=900&q=80", en:{name:"Coastal Linen Shirt",desc:"Stone linen."}, el:{name:"Lino Coastal",desc:"Lino."} },
  { id:"m2", brand:"glamour", cat:"men", type:"tailoring", price:390, img:"https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?auto=format&fit=crop&w=900&q=80", en:{name:"Ink Blazer",desc:"Unstructured."}, el:{name:"Sakaki Ink",desc:"Soft."} },
  { id:"m3", brand:"mare", cat:"men", type:"tailoring", price:220, img:"https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=80", en:{name:"Crete Trouser",desc:"High rise."}, el:{name:"Panteloni Crete",desc:"High."} },
  { id:"m4", brand:"mare", cat:"men", type:"knit", price:180, img:"https://images.unsplash.com/photo-1490114538077-0a7f8cb49891?auto=format&fit=crop&w=900&q=80", en:{name:"Cashmere Crew",desc:"Ivory knit."}, el:{name:"Pleketo Cashmere",desc:"Ivory."} },
  { id:"m5", brand:"glamour", cat:"men", type:"shirts", price:155, img:"https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=900&q=80", en:{name:"Marina Oxford",desc:"White oxford."}, el:{name:"Oxford Marina",desc:"White."} },
  { id:"m6", brand:"glamour", cat:"men", type:"tailoring", price:245, img:"https://images.unsplash.com/photo-1520975916090-3105956dac38?auto=format&fit=crop&w=900&q=80", en:{name:"Harbour Chino",desc:"Stone cotton."}, el:{name:"Chino Harbour",desc:"Stone."} },
  { id:"m7", brand:"mare", cat:"men", type:"knit", price:210, img:"https://images.unsplash.com/photo-1492446845049-9c50cc313f00?auto=format&fit=crop&w=900&q=80", en:{name:"Navy Polo Knit",desc:"Fine polo."}, el:{name:"Polo Navy",desc:"Polo."} },
  { id:"m8", brand:"glamour", cat:"men", type:"shirts", price:175, img:"https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=80", en:{name:"Sand Overshirt",desc:"Marina jacket-shirt."}, el:{name:"Overshirt Sand",desc:"Shirt."} },
  { id:"m9", brand:"mare", cat:"men", type:"tailoring", price:420, img:"https://images.unsplash.com/photo-1520975661595-6453be3f7070?auto=format&fit=crop&w=900&q=80", en:{name:"Navy Dinner Jacket",desc:"Evening jacket."}, el:{name:"Sakaki Dinner",desc:"Night."} },
  { id:"m10", brand:"glamour", cat:"men", type:"shirts", price:135, img:"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80", en:{name:"Black Poplin Shirt",desc:"Day to night."}, el:{name:"Mauro Poplin",desc:"Black."} },
  { id:"m11", brand:"glamour", cat:"men", type:"tailoring", price:280, img:"https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?auto=format&fit=crop&w=900&q=80", en:{name:"Stone Suit Trouser",desc:"Clean crease."}, el:{name:"Panteloni Stone",desc:"Clean."} },
  { id:"m12", brand:"mare", cat:"men", type:"knit", price:165, img:"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=80", en:{name:"Ivory Rollneck",desc:"Fine merino."}, el:{name:"Zivago Ivory",desc:"Merino."} },
  { id:"m13", brand:"glamour", cat:"men", type:"shirts", price:149, img:"https://images.unsplash.com/photo-1516826957135-700dedea698c?auto=format&fit=crop&w=900&q=80", en:{name:"Open Collar Linen",desc:"Heat ready."}, el:{name:"Lino anoihto",desc:"Open."} },
  { id:"m14", brand:"mare", cat:"men", type:"tailoring", price:455, img:"https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=900&q=80", en:{name:"Charcoal Suit Jacket",desc:"Soft construction."}, el:{name:"Sakaki Charcoal",desc:"Soft."} },
  { id:"m15", brand:"glamour", cat:"men", type:"knit", price:195, img:"https://images.unsplash.com/photo-1488161628813-04466f872be2?auto=format&fit=crop&w=900&q=80", en:{name:"Sand Knit Polo",desc:"Resort polo."}, el:{name:"Polo Sand",desc:"Polo."} },
  { id:"m16", brand:"glamour", cat:"men", type:"shirts", price:168, img:"https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=900&q=80", en:{name:"Stripe Marina Shirt",desc:"Blue stripe."}, el:{name:"Rige Marina",desc:"Stripe."} },
  { id:"m17", brand:"mare", cat:"men", type:"tailoring", price:235, img:"https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=900&q=80", en:{name:"Olive Drawstring",desc:"Tailored ease."}, el:{name:"Olive Drawstring",desc:"Ease."} },
  { id:"m18", brand:"glamour", cat:"men", type:"knit", price:225, img:"https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=900&q=80", en:{name:"Bone Sweater",desc:"Weekend knit."}, el:{name:"Poulover Bone",desc:"Weekend."} },
  { id:"m19", brand:"glamour", cat:"men", type:"tailoring", price:365, img:"https://images.unsplash.com/photo-1551232864-3f0890e580d9?auto=format&fit=crop&w=900&q=80", en:{name:"Camel Unstructured",desc:"Light jacket."}, el:{name:"Sakaki Camel",desc:"Light."} },
  { id:"m20", brand:"mare", cat:"men", type:"shirts", price:188, img:"https://images.unsplash.com/photo-1593030103066-0093718efeb9?auto=format&fit=crop&w=900&q=80", en:{name:"White Dinner Shirt",desc:"Evening shirt."}, el:{name:"Poukamisso Dinner",desc:"Night."} },
  { id:"w1", brand:"nisi", cat:"women", type:"dresses", price:260, img:"https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=900&q=80", en:{name:"Ivory Slip Dress",desc:"Bias silk."}, el:{name:"Ivory Slip",desc:"Silk."} },
  { id:"w2", brand:"glamour", cat:"women", type:"shirts", price:165, img:"https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80", en:{name:"Midnight Shirt",desc:"Black poplin."}, el:{name:"Midnight Shirt",desc:"Black."} },
  { id:"w3", brand:"nisi", cat:"women", type:"dresses", price:310, img:"https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=80", en:{name:"Aegean Column",desc:"Long dress."}, el:{name:"Stili Aegean",desc:"Long."} },
  { id:"w4", brand:"nisi", cat:"women", type:"knit", price:195, img:"https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=900&q=80", en:{name:"Soft Culotte Knit",desc:"Wide knit."}, el:{name:"Culotte",desc:"Knit."} },
  { id:"w5", brand:"glamour", cat:"women", type:"shirts", price:170, img:"https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=80", en:{name:"Ivory Silk Shirt",desc:"Open collar."}, el:{name:"Metaxoto Ivory",desc:"Open."} },
  { id:"w6", brand:"nisi", cat:"women", type:"dresses", price:285, img:"https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=900&q=80", en:{name:"Limassol Wrap",desc:"Warm wrap."}, el:{name:"Wrap Lemesos",desc:"Wrap."} },
  { id:"w7", brand:"glamour", cat:"women", type:"tailoring", price:340, img:"https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&w=900&q=80", en:{name:"Camel Coat Dress",desc:"Light tailoring."}, el:{name:"Palto Camel",desc:"Coat."} },
  { id:"w8", brand:"nisi", cat:"women", type:"knit", price:205, img:"https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=900&q=80", en:{name:"Bone Cardigan",desc:"Long knit."}, el:{name:"Zaketa Bone",desc:"Long."} },
  { id:"w9", brand:"glamour", cat:"women", type:"shirts", price:160, img:"https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=900&q=80", en:{name:"Black Column Blouse",desc:"Sharp cuff."}, el:{name:"Blouza Column",desc:"Cuff."} },
  { id:"w10", brand:"nisi", cat:"women", type:"dresses", price:295, img:"https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80", en:{name:"Rose Column",desc:"Long dress."}, el:{name:"Stili Rose",desc:"Long."} },
  { id:"w11", brand:"glamour", cat:"women", type:"dresses", price:275, img:"https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80", en:{name:"Black Slip",desc:"Evening bias."}, el:{name:"Mauro Slip",desc:"Night."} },
  { id:"w12", brand:"nisi", cat:"women", type:"shirts", price:155, img:"https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=900&q=80", en:{name:"Sand Tunic Shirt",desc:"Long line."}, el:{name:"Tunik Sand",desc:"Long."} },
  { id:"w13", brand:"glamour", cat:"women", type:"knit", price:188, img:"https://images.unsplash.com/photo-1550614000-4895a10e1bfd?auto=format&fit=crop&w=900&q=80", en:{name:"Ivory Fine Knit",desc:"Fine knit."}, el:{name:"Lepto Ivory",desc:"Knit."} },
  { id:"w14", brand:"nisi", cat:"women", type:"dresses", price:330, img:"https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80", en:{name:"Gallery Dress",desc:"City night."}, el:{name:"Forema Gallery",desc:"Night."} },
  { id:"w15", brand:"glamour", cat:"women", type:"tailoring", price:365, img:"https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=900&q=80", en:{name:"Stone Tailored Coat",desc:"Light coat."}, el:{name:"Palto Stone",desc:"Coat."} },
  { id:"w16", brand:"nisi", cat:"women", type:"dresses", price:245, img:"https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=900&q=80", en:{name:"Cotton Day Dress",desc:"Marina day."}, el:{name:"Forema imeras",desc:"Day."} },
  { id:"w17", brand:"glamour", cat:"women", type:"shirts", price:175, img:"https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=900&q=80", en:{name:"White Open Shirt",desc:"Over the slip."}, el:{name:"Aspro anoihto",desc:"Open."} },
  { id:"w18", brand:"nisi", cat:"women", type:"knit", price:215, img:"https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80", en:{name:"Black Long Knit",desc:"Column knit."}, el:{name:"Mauro pleketo",desc:"Column."} },
  { id:"w19", brand:"glamour", cat:"women", type:"dresses", price:355, img:"https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=900&q=80", en:{name:"Gold Hour Gown",desc:"Evening length."}, el:{name:"Vradino Gold Hour",desc:"Night."} },
  { id:"w20", brand:"nisi", cat:"women", type:"tailoring", price:290, img:"https://images.unsplash.com/photo-1558171813-4c088753af8f?auto=format&fit=crop&w=900&q=80", en:{name:"Ivory Trouser",desc:"Wide pressed."}, el:{name:"Panteloni Ivory",desc:"Wide."} }
];
let lang=localStorage.getItem("glamour-lang")||"en"; let filter="all"; let cart=JSON.parse(localStorage.getItem("glamour-cart")||"[]"); let activeProduct=null; let activeSize="M";
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function t(key){let v=I18N[lang]; for(const p of key.split(".")) v=v?.[p]; return v??key;}
function applyLang(){$$("[data-i]").forEach(el=>el.textContent=t(el.dataset.i)); $$("[data-ph]").forEach(el=>el.placeholder=t(el.dataset.ph)); document.documentElement.lang=lang==="el"?"el":"en"; $$(".lang-btn").forEach(b=>b.classList.toggle("active",b.dataset.lang===lang)); renderProducts(); renderBrands(); renderCart();}
function brandOf(p){return BRANDS.find(b=>b.id===(p.brand||"glamour"));}
function renderBrands(){const root=document.getElementById("brands"); if(!root)return; root.innerHTML=BRANDS.map(b=>`<article class="brand-card" onclick="setFilter('${b.id}', null)"><h3>${b.name}</h3><p>${b[lang]}</p></article>`).join("");}
function renderProducts(){const root=$("#grid"); if(!root)return; const list=PRODUCTS.filter(p=>filter==="all"||p.cat===filter||p.type===filter||p.brand===filter); root.innerHTML=list.map(p=>`<article class="card" onclick="openProduct('${p.id}')"><div class="card-img"><span class="badge">${brandOf(p).name}</span><img src="${p.img}" alt="${p[lang].name}"></div><div class="card-body"><h3>${p[lang].name}</h3><div class="meta"><span>${p.cat==="men"?t("men"):t("women")}</span><strong>€${p.price}</strong></div></div></article>`).join("");}
function openProduct(id){activeProduct=PRODUCTS.find(p=>p.id===id); activeSize="M"; $("#drawer").style.display="block"; const b=brandOf(activeProduct); $("#drawer-body").innerHTML=`<button class="icon-btn" onclick="closeDrawer()">${t("close")}</button><div class="product-hero"><img src="${activeProduct.img}" alt=""></div><h2>${activeProduct[lang].name}</h2><p style="color:var(--muted);margin:8px 0 16px">${activeProduct[lang].desc}</p><p>${t("soldBy")} <strong>${b.name}</strong></p><strong>€${activeProduct.price}</strong>`;}
function setSize(s,el){activeSize=s; $$(".sizes button").forEach(b=>b.classList.remove("active")); el.classList.add("active");}
function closeDrawer(){$("#drawer").style.display="none";} function closeCart(){$("#cart").style.display="none";} function openCart(){renderCart(); $("#cart").style.display="block";}
function addToCart(){cart.push({id:activeProduct.id,size:activeSize,qty:1}); localStorage.setItem("glamour-cart",JSON.stringify(cart)); updateCount(); closeDrawer();}
function renderCart(){const body=$("#cart-body"); if(!body)return; if(!cart.length){body.innerHTML=`<p>${t("empty")}</p>`; if($("#cart-total"))$("#cart-total").textContent="€0"; return;} let total=0; body.innerHTML=cart.map(item=>{const p=PRODUCTS.find(x=>x.id===item.id); total+=p.price; return `<div class="cart-item"><img src="${p.img}" alt=""><div><strong>${p[lang].name}</strong><div>${item.size}</div></div><div>€${p.price}</div></div>`;}).join(""); if($("#cart-total"))$("#cart-total").textContent="€"+total;}
function updateCount(){const c=$("#count"); if(c)c.textContent=cart.length;} function setLang(next){lang=next; localStorage.setItem("glamour-lang",lang); applyLang();} function setFilter(next,el){filter=next; $$(".chip").forEach(c=>c.classList.remove("active")); if(el)el.classList.add("active"); renderProducts(); document.getElementById("shop")?.scrollIntoView({behavior:"smooth"});}
function partnerApply(e){e.preventDefault(); e.target.reset(); alert("Demo");}
function quiz(mood){const box=$("#quiz-result"); box.style.display="block"; box.textContent=I18N[lang].rec[mood];}
function newsletter(e){e.preventDefault(); e.target.reset(); alert("Thank you.");}
window.openProduct=openProduct; window.setSize=setSize; window.closeDrawer=closeDrawer; window.closeCart=closeCart; window.openCart=openCart; window.addToCart=addToCart; window.setLang=setLang; window.setFilter=setFilter; window.quiz=quiz; window.newsletter=newsletter; window.partnerApply=partnerApply;
applyLang(); updateCount();
