const PRODUCTS = [
  { id:"m1", brand:"glamour", cat:"men", type:"shirts", price:145, img:"https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=900&q=80", en:{name:"Coastal Linen Shirt",desc:"Stone linen."}, el:{name:"Lino Coastal",desc:"Lino."} }
];
let lang=localStorage.getItem("glamour-lang")||"en"; let filter="all"; let cart=JSON.parse(localStorage.getItem("glamour-cart")||"[]"); let activeProduct=null; let activeSize="M";
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function t(key){let v=I18N[lang]; for(const p of key.split(".")) v=v?.[p]; return v??key;}
function applyLang(){$$("[data-i]").forEach(el=>el.textContent=t(el.dataset.i)); $$("[data-ph]").forEach(el=>el.placeholder=t(el.dataset.ph)); document.documentElement.lang=lang==="el"?"el":"en"; $$(".lang-btn").forEach(b=>b.classList.toggle("active",b.dataset.lang===lang)); renderProducts(); renderBrands(); renderCart();}
function brandOf(p){return BRANDS.find(b=>b.id===(p.brand||"glamour"));}
function renderBrands(){const root=document.getElementById("brands"); if(!root)return; root.innerHTML=BRANDS.map(b=>`<article class="brand-card" onclick="setFilter('${b.id}', null)"><h3>${b.name}</h3><p>${b[lang]}</p><div class="comm">${b.model==="own"?(lang==="el"?"Oikos 100%":"House 100%"):(lang==="el"?"Promitheia ":"Commission ")+b.cut+"%"}</div></article>`).join("");}
function renderProducts(){const root=$("#grid"); if(!root)return; const list=PRODUCTS.filter(p=>filter==="all"||p.cat===filter||p.type===filter||p.brand===filter); root.innerHTML=list.map(p=>`<article class="card" onclick="openProduct('${p.id}')"><div class="card-img"><span class="badge">${p.cat==="men"?t("men"):t("women")}</span><img src="${p.img}" alt="${p[lang].name}"></div><div class="card-body"><h3>${p[lang].name}</h3><div class="meta"><span>${brandOf(p).name}</span><strong>€${p.price}</strong></div></div></article>`).join("");}
function openProduct(id){activeProduct=PRODUCTS.find(p=>p.id===id); activeSize="M"; $("#drawer").style.display="block"; const b=brandOf(activeProduct); $("#drawer-body").innerHTML=`<button class="icon-btn" onclick="closeDrawer()">${t("close")}</button><div class="product-hero"><img src="${activeProduct.img}" alt=""></div><h2>${activeProduct[lang].name}</h2><p style="color:var(--muted);margin:8px 0 16px">${activeProduct[lang].desc}</p><p>${t("soldBy")} <strong>${b.name}</strong></p><strong>€${activeProduct.price}</strong><p style="margin-top:16px">${t("size")}</p><div class="sizes">${["XS","S","M","L","XL"].map(s=>`<button class="${s===activeSize?"active":""}" onclick="setSize('${s}', this)">${s}</button>`).join("")}</div><button class="cta" style="width:100%;margin-top:8px" onclick="addToCart()">${t("add")}</button>`;}
function setSize(s,el){activeSize=s; $$(".sizes button").forEach(b=>b.classList.remove("active")); el.classList.add("active");}
function closeDrawer(){$("#drawer").style.display="none";} function closeCart(){$("#cart").style.display="none";} function openCart(){renderCart(); $("#cart").style.display="block";}
function addToCart(){cart.push({id:activeProduct.id,size:activeSize,qty:1}); localStorage.setItem("glamour-cart",JSON.stringify(cart)); updateCount(); closeDrawer();}
function renderCart(){const body=$("#cart-body"); if(!body)return; if(!cart.length){body.innerHTML=`<p>${t("empty")}</p>`; $("#cart-total").textContent="€0"; return;} let total=0; body.innerHTML=cart.map(item=>{const p=PRODUCTS.find(x=>x.id===item.id); total+=p.price; return `<div class="cart-item"><img src="${p.img}" alt=""><div><strong>${p[lang].name}</strong><div>${item.size}</div></div><div>€${p.price}</div></div>`;}).join(""); $("#cart-total").textContent="€"+total;}
function updateCount(){const c=$("#count"); if(c)c.textContent=cart.length;} function setLang(next){lang=next; localStorage.setItem("glamour-lang",lang); applyLang();} function setFilter(next,el){filter=next; $$(".chip").forEach(c=>c.classList.remove("active")); if(el)el.classList.add("active"); renderProducts(); document.getElementById("shop")?.scrollIntoView({behavior:"smooth"});}
function partnerApply(e){e.preventDefault(); e.target.reset(); alert(lang==="el"?"Demo.":"Demo.");}
function quiz(mood){const box=$("#quiz-result"); box.style.display="block"; box.textContent=I18N[lang].rec[mood];}
function newsletter(e){e.preventDefault(); e.target.reset(); alert(lang==="el"?"Efharisto.":"Thank you.");}
window.openProduct=openProduct; window.setSize=setSize; window.closeDrawer=closeDrawer; window.closeCart=closeCart; window.openCart=openCart; window.addToCart=addToCart; window.setLang=setLang; window.setFilter=setFilter; window.quiz=quiz; window.newsletter=newsletter; window.partnerApply=partnerApply;
applyLang(); updateCount();
